# Numpy

>NumPy is the core tools for performing numerical computing with Python. It is used by many other scientific libraries such as Pandas, matplotlib.

## Objectives: 
        1. create 1D and 2D arrays, including some special arrays ones, diag, zeros, ...
        2. slice, index, reshape, sort an array   
        3. preform numerical operations on arrays 

In [1]:
# import package NumPy 
import numpy as np

### Create 1-dimensional arrays (column vectors)

In [2]:
x = np.array([1, 2, 10, 2, 1 ])

In [3]:
type(x)

numpy.ndarray

In [4]:
x

array([ 1,  2, 10,  2,  1])

In [5]:
# shape of the array, which shall be a 5 x 1 column vector
x.shape

(5,)

In [6]:
# number of rows 
len(x)

5

In [7]:
# first element of the array x
x[0]

1

In [8]:
# second element of the array x
x[1]

2

In [9]:
# last element of the array x
x[-1]

1

In [10]:
# first 2 elements of the array x
x[:2]

array([1, 2])

In [11]:
# last 2 elements of the array x
x[-2:]

array([2, 1])

In [12]:
# from the 2nd to the 4th elements of the array x
x[1:4]

array([ 2, 10,  2])

In [13]:
# dimension of the array x
x.ndim

1

### Create 2-dimensional arrays (matrices)

In [14]:
y = np.array([[1,2], [3,4]])

In [15]:
y

array([[1, 2],
       [3, 4]])

In [16]:
# you can also use list to create a 2-dim array 
n1 = [1, 2, 3]
n2 = [4, 5, 6]
n3 = [7, 8, 9]
n4 = [10, 11, 12]
m = np.array([n1, n2, n3, n4])

In [17]:
m

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
m.ndim

2

In [19]:
m.shape # (# rows, # columns)

(4, 3)

In [20]:
len(m)

4

In [21]:
# the 1st row of matrix m
m[0,:]

array([1, 2, 3])

In [22]:
# the first two rows of matrix m
m[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
# the 1st column of matrix m
m[:,0]

array([ 1,  4,  7, 10])

In [24]:
# the last two column of matrix m
m[:,-2:]

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

In [25]:
# the 4th row and 2nd column element (answer shall be 11)
m[3,1]

11

### Create special 2-dimensional arrays (ones, zeros, diag, eye, empty, random)

In [26]:
# diag matrix 
np.diag((5,5,1,1))

array([[5, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [27]:
# matrix with all entries equal to 1
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
# zero matrix 
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [29]:
# identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
# array of normally distributed values
np.random.normal(size=4)

array([ 0.23973047,  0.12029351, -2.25294415,  0.89833212])

In [31]:
# array of normally distributed values
np.random.normal(size=(4,4))

array([[-0.21347282, -1.74292885,  0.44332602, -1.67026125],
       [-0.67949249,  1.70277704,  0.59998401, -1.31791443],
       [-2.11214613, -1.54213709, -2.09751456,  0.45726634],
       [-2.2402325 ,  0.46698471,  0.35356169, -0.96878535]])

## data types

In [32]:
x = np.array([1, 2, 3])
x.dtype

dtype('int64')

In [33]:
x

array([1, 2, 3])

In [34]:
x = np.array([1., 2, 3.5])
x.dtype

dtype('float64')

In [35]:
x

array([1. , 2. , 3.5])

In [36]:
x = np.array([1, 2, 3], dtype=float)
x.dtype

dtype('float64')

In [37]:
x = np.array([1, 2, 3])
x = x.astype(float)
x

array([1., 2., 3.])

In [38]:
# If you mix types, the most complex type is used
np.array([1.0, 1, "oups"])

array(['1.0', '1', 'oups'], dtype='<U32')

## Indexing with boolean masks

In [39]:
x = np.array([-10, -5, -0.1, 0, 2, 5, 6, 10000])

In [40]:
# check each element in array x whether it is less than 0 or not 
x<0

array([ True,  True,  True, False, False, False, False, False])

In [41]:
# pick all elements which are less than 0 in array x 
x[x<0]

array([-10. ,  -5. ,  -0.1])

In [42]:
# check each element in array x whether it is even or not 
x %  2 == 0

array([ True, False, False,  True,  True, False,  True,  True])

In [43]:
# pick all even elements in array x 
x[x % 2 == 0]

array([-1.e+01,  0.e+00,  2.e+00,  6.e+00,  1.e+04])

In [44]:
# convert all even elements to integers  
x[x % 2 == 0].astype(int)

array([  -10,     0,     2,     6, 10000])

## Numerical operations

In [45]:
A = np.array([[4, 7], 
              [2, 6]])

B = np.array([[0.6, -0.7],
              [-0.2, 0.4]])

In [46]:
A + B

array([[4.6, 6.3],
       [1.8, 6.4]])

In [47]:
A - B

array([[3.4, 7.7],
       [2.2, 5.6]])

In [48]:
# elementwise product
A * B

array([[ 2.4, -4.9],
       [-0.4,  2.4]])

In [49]:
# matrix product
A.dot(B)

array([[ 1.00000000e+00,  3.33066907e-16],
       [-1.11022302e-16,  1.00000000e+00]])

In [50]:
A.dot(B).round()

array([[ 1.,  0.],
       [-0.,  1.]])

In [51]:
# elementwise division 
A/B

array([[  6.66666667, -10.        ],
       [-10.        ,  15.        ]])

## reshape 

In [52]:
a = np.array([[1,2,3],[4,5,6]])

In [53]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
a.shape

(2, 3)

In [55]:
# reshape to a 3x2 array 
b = a.reshape(3,2)

In [56]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [57]:
b.shape

(3, 2)

In [58]:
# reshape to a 1x6 array 
c =  a.reshape((1,6))

In [59]:
c 

array([[1, 2, 3, 4, 5, 6]])

In [60]:
c.shape

(1, 6)

## sorting 

In [61]:
X = np.array([5,1,10,2,7,8])
X.sort() # inplace
X

array([ 1,  2,  5,  7,  8, 10])

In [62]:
X = np.array([5,1,10,2,7,8])
np.sort(X)

array([ 1,  2,  5,  7,  8, 10])

# Summary
    1. How to create arrays with : array, ones, diag, zeros, ...
    2. How to check array's shape and dimensions
    3. Perform slicing and indexing arrays
    4. How to use operators. Keep in mind that * operator is an element-wise operation.
    5. How to reshape and sort an array 
    6. Reference: http://numpy.org 
    


## Next Pandas  ... 